name: drawidgets
description: >-
  Utilities that enhance Flutter development 
  powered by the Drawidgets ecosystem.
version: 0.0.1
repository: https://github.com/drawidgets/drawidgets

environment:
  sdk: ^3.5.4
  flutter: ">=3.24.4"

dependencies:
  flutter: {sdk: flutter}
  path: ^1.9.0

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^5.0.0
